const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('#nav');
function closeMenu(){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}
toggle.addEventListener('click',()=>{const isOpen=toggle.getAttribute('aria-expanded')==='true';nav.classList.toggle('open',!isOpen);toggle.setAttribute('aria-expanded',String(!isOpen))});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();if(document.activeElement.closest('#nav'))toggle.focus()}});
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){document.documentElement.classList.add('js');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}
const photos=Array.from(document.querySelectorAll('[data-photo]'));const lightbox=document.querySelector('.lightbox');let photoIndex=0;let photoTrigger=null;
function showPhoto(index){photoIndex=(index+photos.length)%photos.length;const source=photos[photoIndex];const image=lightbox.querySelector('img');image.src=source.dataset.photo;image.alt=source.querySelector('img').alt;lightbox.querySelector('figcaption').textContent=source.dataset.caption;lightbox.querySelector('.photo-count').textContent=`${photoIndex+1} / ${photos.length}`}
photos.forEach((button,index)=>button.addEventListener('click',()=>{photoTrigger=button;showPhoto(index);lightbox.showModal();document.body.classList.add('has-lightbox')}));
lightbox.querySelector('.lightbox-close').addEventListener('click',()=>lightbox.close());lightbox.querySelector('.photo-prev').addEventListener('click',()=>showPhoto(photoIndex-1));lightbox.querySelector('.photo-next').addEventListener('click',()=>showPhoto(photoIndex+1));
lightbox.addEventListener('click',e=>{const r=lightbox.getBoundingClientRect();if(e.target===lightbox&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))lightbox.close()});lightbox.addEventListener('close',()=>{document.body.classList.remove('has-lightbox');photoTrigger?.focus()});lightbox.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();showPhoto(photoIndex+1)}if(e.key==='ArrowLeft'){e.preventDefault();showPhoto(photoIndex-1)}});
